name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: basic JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Meeee
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time}}"
      - name: list files before checkout
        run: ls -a
      - name: check out branch
        uses: actions/checkout@v1
      - name: list files after checkout
        run: ls -a 
