name: Actions with variables

on: [push]
env: 
  ENV_VAR: This env_var is visible from all commits

jobs:
  push-random-file-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Push random file
        run: |
          pwd
          ls -a
          echo "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "a_bot@bot.com"
          git config --global user.name "a_bot"
          git fetch 
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo "This is a random number in a file: $RANDOM" >> random.txt
          ls -a
          git add -A
          git commit -m "Added a file random.txt"
          git push


      - name: Create an issue using the REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/issues \
          --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
          --header 'content-type: appllication/json' \
          --data '{"title":"Issue from API","body":"This issue relates to commit ${{github.sha}}" }'
    