name: Actions with variables

on: [push]
env: 
  ENV_VAR: This env_var is visible from all commits

jobs:
  push-random-file-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create an issue using the REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/issues \
          --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
          --header 'content-type: appllication/json' \
          --data '{"title":"Issue from API","body":"This issue relates to commit ${{github.sha}}" }'
    