name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echoes a string
        run: echo "Hello, there"
      - name:  multiline script 
        run: |
          node -v
          npm -v
      - name: python script
        run: |
          import platform
          print(f"Running on {platform.processor()}")
        shell: python

  run-shell-command-on-windows:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: creates a directory and does stuff
        run:  |
         mkdir a_directory
         cd a_directory
         Get-Location
      - name: run same in bash
        run: pwd
        shell: bash
