name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echoes a string; this should now fail!
        run: echo "Hello, there"
      - name:  multiline script 
        run: |
          node -v
          npm -v
      - name: python script
        run: |
          import platform
          print(f"Running on {platform.processor()}")
        shell: python
