name: Functions

on:
  push:
    branches:
      - '!develop'

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: current location in agent
        run: |
          echo "we are in "
          pwd
      - name: failed step
        run: eccho "this will not run; echo with 2 c's??"
      - name: first conditional step
        if: failure()
        run: echo "The previous step failed but I ran"
      - name: second conditional step
        if: always()
        run: echo "I should always run!!"
      - name: another intentional failure
        run: eccho "Mannnn, again 2 c's?"
      - name: one more conditional step
        if: success()
        run: echo "I should not run!"
  matrix_second_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a_number:
          - 10
          - 18
          - 16
          - 25
          - 28
    steps:
      - name: prints a number
        run: echo "${{matrix.a_number}}"
